module.exports = {
    SAVE_QUERY_PARAMS: 'SAVE_QUERY_PARAMS',
    SAVE_SELECTION: 'SAVE_SELECTION',
    SELECTED_TYPE: 'SELECTED_TYPE',
    SAVE_RESULTS : 'SAVE_RESULTS',
    FETCH_ARTICLES_DATA : 'FETCH_ARTICLES',
    FETCH_ARTICLES_FILTER : 'FETCH_ARTICLES_FILTER',
    SAVE_ARTICLES_FILTER_DATA : 'SAVE_ARTICLES_FILTER_DATA',
    SELECT_FILTER_BY_USER_DATA : 'SELECT_FILTER_BY_USER_DATA',
}
